from __future__ import annotations

import json
import shutil
from pathlib import Path

from rich.console import Console

from .config import DELIVERABLES_DIR, ensure_dirs
from .store import all_call_dirs

console = Console()


def export() -> None:
    ensure_dirs()
    transcript_dir = DELIVERABLES_DIR / "transcripts"
    recording_dir = DELIVERABLES_DIR / "recordings"
    transcript_dir.mkdir(parents=True, exist_ok=True)
    recording_dir.mkdir(parents=True, exist_ok=True)

    rows: list[str] = [
        "# Call Index",
        "",
        "This file is generated by `python -m pgai_voice_bot.export_deliverables`.",
        "",
        "| # | Call SID | Scenario | Transcript | Recording | Notes |",
        "|---:|---|---|---|---|---|",
    ]

    call_dirs = all_call_dirs()
    for idx, path in enumerate(call_dirs, start=1):
        call_sid = path.name
        metadata = read_json(path / "metadata.json")
        state = read_json(path / "state.json")
        scenario = metadata.get("scenario_id") or state.get("scenario_id") or "unknown"
        transcript_src = path / "transcript.txt"
        recording_src = path / "recording.mp3"
        transcript_name = f"transcript-{idx:02d}-{scenario}.txt"
        recording_name = f"recording-{idx:02d}-{scenario}.mp3"
        notes = []

        if transcript_src.exists():
            shutil.copy2(transcript_src, transcript_dir / transcript_name)
            transcript_link = f"transcripts/{transcript_name}"
        else:
            transcript_link = "MISSING"
            notes.append("missing transcript")

        if recording_src.exists():
            shutil.copy2(recording_src, recording_dir / recording_name)
            recording_link = f"recordings/{recording_name}"
        else:
            recording_link = "MISSING"
            notes.append("missing recording")

        rows.append(
            f"| {idx} | `{call_sid}` | `{scenario}` | {transcript_link} | {recording_link} | {', '.join(notes) or 'ready'} |"
        )

    (DELIVERABLES_DIR / "CALL_INDEX.md").write_text("\n".join(rows) + "\n", encoding="utf-8")
    console.print(f"Exported {len(call_dirs)} calls to {DELIVERABLES_DIR}")
    if len(call_dirs) < 10:
        console.print("[yellow]Warning:[/yellow] fewer than 10 calls found. The challenge requires at least 10.")


def read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


if __name__ == "__main__":
    export()
